## gCRL-VAE applied on a simple simulated dataset

- Load example adata (with TF communities already specified)
- Compute eigengenes
- Train gCRL-VAE

In [1]:
# ensuring all packages are reloaded each time I run a cell
%load_ext autoreload
%autoreload 2

In [2]:
# importing
import scanpy as sc
from gcrl.training.train_gcrl_vae import train_gcrl_vae
from gcrl.training.train_gcrl_vae import VAEConfig
from gcrl.grn.eigengenes import compute_eigengenes

In [3]:
# loading data
adata = sc.read_h5ad("../../data/example/adata.h5ad")
adata

AnnData object with n_obs × n_vars = 2000 × 1087
    obs: 'intervention', 'cell_type', 'intervention_comm', 'set'
    var: 'kind', 'community'

In [4]:
adata.X

array([[-1.2016395 , -0.2003566 ,  0.29787228, ..., -1.2956456 ,
         0.48420304, -0.87598544],
       [-2.075858  ,  0.38679   , -0.3809394 , ...,  1.2222987 ,
         0.8771311 ,  1.8957161 ],
       [ 0.5517998 ,  1.6879523 ,  1.6434073 , ...,  0.14092468,
        -0.24709606, -0.30600578],
       ...,
       [-1.5627143 , -0.05961697, -0.7534087 , ..., -1.2034842 ,
         0.99365985, -1.8343128 ],
       [-0.47931707,  0.04802489, -0.59183484, ..., -1.0852625 ,
        -0.6143062 ,  0.22651327],
       [-0.99326056, -0.9787096 , -0.13516974, ..., -0.08082284,
         2.3217251 ,  0.28029335]], dtype=float32)

In [5]:
adata.obs

              intervention  cell_type  intervention_comm       set
unperturbed_0  unperturbed          1                NaN  training
unperturbed_1  unperturbed          1                NaN  training
unperturbed_2  unperturbed          1                NaN  training
unperturbed_3  unperturbed          1                NaN  training
unperturbed_4  unperturbed          1                NaN  training
...                    ...        ...                ...       ...
pert_c4_195      TF_c4_n15          1                4.0  training
pert_c4_196      TF_c4_n15          1                4.0  training
pert_c4_197      TF_c4_n15          1                4.0  training
pert_c4_198      TF_c4_n15          1                4.0  training
pert_c4_199      TF_c4_n15          1                4.0  training

[2000 rows x 4 columns]

In [6]:
adata.var

          kind  community
gene_name
TF_c0_n0    TF          0
TF_c0_n1    TF          0
TF_c0_n2    TF          0
TF_c0_n3    TF          0
TF_c0_n4    TF          0
...        ...        ...
TG_995      TG          0
TG_996      TG          1
TG_997      TG          4
TG_998      TG          3
TG_999      TG          4

[1087 rows x 2 columns]

In [7]:
# computing eigengenes
compute_eigengenes(adata)
adata

AnnData object with n_obs × n_vars = 2000 × 1087
    obs: 'intervention', 'cell_type', 'intervention_comm', 'set'
    var: 'kind', 'community'
    uns: 'X_comm_eig_comm_ids', 'X_comm_eig_global_index', 'comm_eig_meta'
    obsm: 'X_comm_eig'

In [8]:
# gCRL-VAE configuration
cfg = VAEConfig()
cfg.batch_size = 128
cfg.outdir = "../../results/simulated/example/vae"
cfg

VAEConfig(outdir='../../results/simulated/example/vae', intervention_mapping='hard', batch_size=128, epochs=50, lr=0.002, beta_kld=0.001, alpha_rec=1.0, lambda_mcc=1.0, num_workers=0, seed=0)

In [9]:
# training gCRL-AE
res = train_gcrl_vae(adata=adata, cfg = cfg)

[Epoch 1] loss=0.1496 loss_rec=0.9067 loss_kld=0.0669
[Epoch 2] loss=-0.0505 loss_rec=0.9034 loss_kld=0.3050
[Epoch 3] loss=-0.0854 loss_rec=0.8862 loss_kld=0.7751
[Epoch 4] loss=-0.1212 loss_rec=0.8567 loss_kld=1.8176
[Epoch 5] loss=-0.1528 loss_rec=0.8274 loss_kld=3.1031
[Epoch 6] loss=-0.1787 loss_rec=0.8028 loss_kld=3.8121
[Epoch 7] loss=-0.2041 loss_rec=0.7774 loss_kld=4.0572
[Epoch 8] loss=-0.2261 loss_rec=0.7555 loss_kld=4.2242
[Epoch 9] loss=-0.2490 loss_rec=0.7328 loss_kld=4.4241
[Epoch 10] loss=-0.2706 loss_rec=0.7107 loss_kld=4.6414
[Epoch 11] loss=-0.2909 loss_rec=0.6899 loss_kld=4.8013
[Epoch 12] loss=-0.3107 loss_rec=0.6691 loss_kld=5.0616
[Epoch 13] loss=-0.3281 loss_rec=0.6512 loss_kld=5.4178
[Epoch 14] loss=-0.3455 loss_rec=0.6329 loss_kld=5.6925
[Epoch 15] loss=-0.3629 loss_rec=0.6150 loss_kld=5.9286
[Epoch 16] loss=-0.3786 loss_rec=0.5982 loss_kld=6.2626
[Epoch 17] loss=-0.3934 loss_rec=0.5832 loss_kld=6.6613
[Epoch 18] loss=-0.4063 loss_rec=0.5693 loss_kld=6.9782
[Epoch 19] loss=-0.4192 loss_rec=0.5563 loss_kld=7.2277
[Epoch 20] loss=-0.4316 loss_rec=0.5429 loss_kld=7.5017
[Epoch 21] loss=-0.4431 loss_rec=0.5309 loss_kld=7.7396
[Epoch 22] loss=-0.4568 loss_rec=0.5169 loss_kld=8.1134
[Epoch 23] loss=-0.4684 loss_rec=0.5049 loss_kld=8.4560
[Epoch 24] loss=-0.4786 loss_rec=0.4942 loss_kld=8.6488
[Epoch 25] loss=-0.4855 loss_rec=0.4865 loss_kld=8.9521
[Epoch 26] loss=-0.4948 loss_rec=0.4776 loss_kld=9.1459
[Epoch 27] loss=-0.5044 loss_rec=0.4671 loss_kld=9.3063
[Epoch 28] loss=-0.5123 loss_rec=0.4584 loss_kld=9.5160
[Epoch 29] loss=-0.5206 loss_rec=0.4505 loss_kld=9.7615
[Epoch 30] loss=-0.5278 loss_rec=0.4424 loss_kld=9.9408
[Epoch 31] loss=-0.5350 loss_rec=0.4352 loss_kld=10.0791
[Epoch 32] loss=-0.5420 loss_rec=0.4280 loss_kld=10.1735
[Epoch 33] loss=-0.5504 loss_rec=0.4191 loss_kld=10.4030
[Epoch 34] loss=-0.5564 loss_rec=0.4130 loss_kld=10.6509
[Epoch 35] loss=-0.5631 loss_rec=0.4059 loss_kld=10.8924
[Epoch 36] loss=-0.5681 loss_rec=0.4010 loss_kld=10.8386
[Epoch 37] loss=-0.5698 loss_rec=0.3987 loss_kld=10.8354
[Epoch 38] loss=-0.5763 loss_rec=0.3928 loss_kld=10.7994
[Epoch 39] loss=-0.5820 loss_rec=0.3858 loss_kld=10.9206
[Epoch 40] loss=-0.5849 loss_rec=0.3829 loss_kld=11.0060
[Epoch 41] loss=-0.5916 loss_rec=0.3763 loss_kld=11.0369
[Epoch 42] loss=-0.5970 loss_rec=0.3708 loss_kld=11.1905
[Epoch 43] loss=-0.6016 loss_rec=0.3663 loss_kld=11.2876
[Epoch 44] loss=-0.6082 loss_rec=0.3598 loss_kld=11.2458
[Epoch 45] loss=-0.6119 loss_rec=0.3561 loss_kld=11.3262
[Epoch 46] loss=-0.6159 loss_rec=0.3517 loss_kld=11.5139
[Epoch 47] loss=-0.6189 loss_rec=0.3486 loss_kld=11.4694
[Epoch 48] loss=-0.6232 loss_rec=0.3442 loss_kld=11.4578
[Epoch 49] loss=-0.6265 loss_rec=0.3410 loss_kld=11.4578
[Epoch 50] loss=-0.6303 loss_rec=0.3368 loss_kld=11.6524

In [10]:
adata

AnnData object with n_obs × n_vars = 2000 × 1087
    obs: 'intervention', 'cell_type', 'intervention_comm', 'set'
    var: 'kind', 'community'
    uns: 'X_comm_eig_comm_ids', 'X_comm_eig_global_index', 'comm_eig_meta', 'gcrl_preproc'
    obsm: 'X_comm_eig'
    layers: 'X_log1p'

In [11]:
res[0]

GCRLVAE(
  (encoder): Sequential(
    (0): Linear(in_features=1087, out_features=512, bias=True)
    (1): LeakyReLU(negative_slope=0.1, inplace=True)
    (2): Linear(in_features=512, out_features=256, bias=True)
    (3): LeakyReLU(negative_slope=0.1, inplace=True)
  )
  (fc_mu): Linear(in_features=256, out_features=6, bias=True)
  (fc_var): Linear(in_features=256, out_features=6, bias=True)
  (decoder): Sequential(
    (0): Linear(in_features=6, out_features=256, bias=True)
    (1): LeakyReLU(negative_slope=0.1, inplace=True)
    (2): Linear(in_features=256, out_features=512, bias=True)
    (3): LeakyReLU(negative_slope=0.1, inplace=True)
    (4): Linear(in_features=512, out_features=1087, bias=True)
    (5): LeakyReLU(negative_slope=0.1, inplace=True)
  )
)

In [12]:
res[1]

[{'loss': 0.1496119350194931,
  'loss_rec': 0.9066528007388115,
  'loss_kld': 0.06694316142238677,
  'epoch': 1},
 {'loss': -0.0505102276802063,
  'loss_rec': 0.9034006968140602,
  'loss_kld': 0.3050184156745672,
  'epoch': 2},
 {'loss': -0.08538573235273361,
  'loss_rec': 0.886207103729248,
  'loss_kld': 0.7750917449593544,
  'epoch': 3},
 {'loss': -0.12121637910604477,
  'loss_rec': 0.856691800057888,
  'loss_kld': 1.8176014572381973,
  'epoch': 4},
 {'loss': -0.15276837348937988,
  'loss_rec': 0.8274411559104919,
  'loss_kld': 3.103067398071289,
  'epoch': 5},
 {'loss': -0.1786949709057808,
  'loss_rec': 0.8027511239051819,
  'loss_kld': 3.812097191810608,
  'epoch': 6},
 {'loss': -0.20414620637893677,
  'loss_rec': 0.7774211019277573,
  'loss_kld': 4.057249873876572,
  'epoch': 7},
 {'loss': -0.22612539678812027,
  'loss_rec': 0.7555417791008949,
  'loss_kld': 4.224212050437927,
  'epoch': 8},
 {'loss': -0.24903447926044464,
  'loss_rec': 0.7327983602881432,
  'loss_kld': 4.424076616764069,
  'epoch': 9},
 {'loss': -0.27058231085538864,
  'loss_rec': 0.7107392251491547,
  'loss_kld': 4.641432881355286,
  'epoch': 10},
 {'loss': -0.29086247831583023,
  'loss_rec': 0.6898886486887932,
  'loss_kld': 4.801265299320221,
  'epoch': 11},
 {'loss': -0.31071043014526367,
  'loss_rec': 0.6690545901656151,
  'loss_kld': 5.061578810214996,
  'epoch': 12},
 {'loss': -0.32806137949228287,
  'loss_rec': 0.6511977091431618,
  'loss_kld': 5.417798578739166,
  'epoch': 13},
 {'loss': -0.34552154690027237,
  'loss_rec': 0.6329288929700851,
  'loss_kld': 5.6924654841423035,
  'epoch': 14},
 {'loss': -0.36293943226337433,
  'loss_rec': 0.6149685457348824,
  'loss_kld': 5.928634703159332,
  'epoch': 15},
 {'loss': -0.37859901785850525,
  'loss_rec': 0.5982457101345062,
  'loss_kld': 6.262551665306091,
  'epoch': 16},
 {'loss': -0.39338552951812744,
  'loss_rec': 0.583240233361721,
  'loss_kld': 6.661333620548248,
  'epoch': 17},
 {'loss': -0.4063439518213272,
  'loss_rec': 0.569333903491497,
  'loss_kld': 6.978227078914642,
  'epoch': 18},
 {'loss': -0.419238917529583,
  'loss_rec': 0.556273527443409,
  'loss_kld': 7.227677166461945,
  'epoch': 19},
 {'loss': -0.43158528208732605,
  'loss_rec': 0.5429146140813828,
  'loss_kld': 7.50171023607254,
  'epoch': 20},
 {'loss': -0.4431045353412628,
  'loss_rec': 0.5308524370193481,
  'loss_kld': 7.7396475076675415,
  'epoch': 21},
 {'loss': -0.45675618201494217,
  'loss_rec': 0.5168994441628456,
  'loss_kld': 8.113376140594482,
  'epoch': 22},
 {'loss': -0.4683922752737999,
  'loss_rec': 0.5048651769757271,
  'loss_kld': 8.455955862998962,
  'epoch': 23},
 {'loss': -0.4785953350365162,
  'loss_rec': 0.49418847635388374,
  'loss_kld': 8.648842215538025,
  'epoch': 24},
 {'loss': -0.485492505133152,
  'loss_rec': 0.4865215830504894,
  'loss_kld': 8.952123045921326,
  'epoch': 25},
 {'loss': -0.49475548416376114,
  'loss_rec': 0.47755470126867294,
  'loss_kld': 9.145914673805237,
  'epoch': 26},
 {'loss': -0.504354789853096,
  'loss_rec': 0.4670538529753685,
  'loss_kld': 9.306321620941162,
  'epoch': 27},
 {'loss': -0.5123012065887451,
  'loss_rec': 0.4583734758198261,
  'loss_kld': 9.516026377677917,
  'epoch': 28},
 {'loss': -0.520564615726471,
  'loss_rec': 0.4505236744880676,
  'loss_kld': 9.76150119304657,
  'epoch': 29},
 {'loss': -0.5277931578457355,
  'loss_rec': 0.4423883967101574,
  'loss_kld': 9.940800666809082,
  'epoch': 30},
 {'loss': -0.5350044444203377,
  'loss_rec': 0.4352474585175514,
  'loss_kld': 10.079140186309814,
  'epoch': 31},
 {'loss': -0.5420144125819206,
  'loss_rec': 0.427971426397562,
  'loss_kld': 10.173464059829712,
  'epoch': 32},
 {'loss': -0.5503788590431213,
  'loss_rec': 0.41914020106196404,
  'loss_kld': 10.402966856956482,
  'epoch': 33},
 {'loss': -0.5563829392194748,
  'loss_rec': 0.4129551760852337,
  'loss_kld': 10.650940775871277,
  'epoch': 34},
 {'loss': -0.5630936473608017,
  'loss_rec': 0.40585751459002495,
  'loss_kld': 10.892439484596252,
  'epoch': 35},
 {'loss': -0.5680883452296257,
  'loss_rec': 0.4010350927710533,
  'loss_kld': 10.838576793670654,
  'epoch': 36},
 {'loss': -0.5697922632098198,
  'loss_rec': 0.398697417229414,
  'loss_kld': 10.835434794425964,
  'epoch': 37},
 {'loss': -0.5763053745031357,
  'loss_rec': 0.3927609845995903,
  'loss_kld': 10.799439907073975,
  'epoch': 38},
 {'loss': -0.5820088908076286,
  'loss_rec': 0.3857751414179802,
  'loss_kld': 10.920621871948242,
  'epoch': 39},
 {'loss': -0.584909476339817,
  'loss_rec': 0.3829075060784817,
  'loss_kld': 11.00599718093872,
  'epoch': 40},
 {'loss': -0.5916047245264053,
  'loss_rec': 0.37634026631712914,
  'loss_kld': 11.036922335624695,
  'epoch': 41},
 {'loss': -0.5969645604491234,
  'loss_rec': 0.3707806095480919,
  'loss_kld': 11.190547943115234,
  'epoch': 42},
 {'loss': -0.6016125530004501,
  'loss_rec': 0.36632539331912994,
  'loss_kld': 11.28755009174347,
  'epoch': 43},
 {'loss': -0.6081645265221596,
  'loss_rec': 0.3598092198371887,
  'loss_kld': 11.245783686637878,
  'epoch': 44},
 {'loss': -0.6118642017245293,
  'loss_rec': 0.35605548694729805,
  'loss_kld': 11.326182126998901,
  'epoch': 45},
 {'loss': -0.6158860921859741,
  'loss_rec': 0.3517419546842575,
  'loss_kld': 11.513949155807495,
  'epoch': 46},
 {'loss': -0.6188735365867615,
  'loss_rec': 0.34859469532966614,
  'loss_kld': 11.469416975975037,
  'epoch': 47},
 {'loss': -0.6231596022844315,
  'loss_rec': 0.3441639095544815,
  'loss_kld': 11.457759141921997,
  'epoch': 48},
 {'loss': -0.626476563513279,
  'loss_rec': 0.3410439267754555,
  'loss_kld': 11.457828164100647,
  'epoch': 49},
 {'loss': -0.6302652731537819,
  'loss_rec': 0.3367840610444546,
  'loss_kld': 11.65243113040924,
  'epoch': 50}]

In [14]:
# performances = evaluate(res[0], adata)