In [1]:

# imports
import pickle
import numpy as np
import pandas as pd
import anndata as ad
import scanpy as sc
import random
from pathlib import Path
import sys
repo_parent = Path('./code/SERGIO').resolve().parent
sys.path.insert(0, str(repo_parent))
from SERGIO.sergio import sergio

# parameters
grn_folder = '../generated_data/'
noise_params = 1
decays=0.8 
sampling_state=15
noise_type='dpd'

In [24]:
sim = sergio(number_genes=282, # to be read from the grn_folder
             number_bins = 1, # always one
             number_sc = 100, # to be taken as a input
             noise_params = noise_params, 
             decays=decays, 
             sampling_state=sampling_state, 
             noise_type=noise_type)

'../generated_data/input_targets.txt'

In [25]:
sim.build_graph(input_file_taregts = grn_folder + 'input_targets.txt', 
                input_file_regs = grn_folder + 'input_regs.txt', 
                shared_coop_state = 2)

In [26]:
sim.simulate()
expr = sim.getExpressions()
expr_clean = np.concatenate(expr, axis = 1)

df = pd.DataFrame(expr_clean)
df

Start simulating new level
There are 4 genes to simulate in this layer
Done with current level
Start simulating new level
There are 8 genes to simulate in this layer
Done with current level
Start simulating new level
There are 14 genes to simulate in this layer
Done with current level
Start simulating new level
There are 26 genes to simulate in this layer
Done with current level
Start simulating new level
There are 30 genes to simulate in this layer
Done with current level
Start simulating new level
There are 200 genes to simulate in this layer
Done with current level

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,2.379870,6.232221,2.389488,7.400163,2.838763,6.520937,1.896109,4.930669,6.001150,4.418466,...,2.341818,4.464269,2.425303,6.568907,2.546079,3.420737,5.277906,8.874162,7.807674,1.976354
1,12.161910,5.548424,4.561363,5.135313,4.015736,3.588552,4.218921,6.007644,6.077683,10.043033,...,5.312931,6.594047,4.762569,5.933433,5.604813,8.820370,9.307691,10.159700,4.245665,3.668386
2,1.845266,0.084667,3.435281,1.585042,2.999485,1.743746,0.480009,1.418461,2.117587,2.004631,...,4.334829,2.670124,3.038248,2.073127,3.364473,0.829712,0.869288,1.254590,1.676744,3.516427
3,7.554217,7.769491,2.139767,3.610090,7.657577,5.598295,6.187488,8.384993,4.449465,6.414475,...,3.163281,5.013460,7.430260,9.017039,3.091773,9.289331,7.783353,7.474117,7.460396,3.355490
4,5.241872,3.640982,4.273661,1.095790,3.988296,4.802391,2.935278,5.918449,3.674064,0.268031,...,6.727905,2.688516,4.224588,2.079507,3.858548,6.137328,5.744765,0.889173,0.560470,3.328461
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,6.036187,7.678715,9.462883,9.170289,14.196692,5.017043,12.974995,9.239402,4.633327,11.009424,...,5.702336,8.720925,13.242578,11.042705,13.708944,8.995269,8.495112,9.363164,8.589304,10.814824
278,7.796701,8.876296,10.512581,9.151902,8.258620,12.044395,6.143897,7.761328,13.676517,9.246103,...,7.954852,8.622978,9.270345,7.167247,8.829891,14.137110,13.467303,7.068777,5.813891,9.341576
279,4.344270,8.325623,10.960445,7.108395,6.334974,7.676485,10.148092,8.017012,9.200264,15.853605,...,17.441559,6.300826,6.985246,12.997103,7.487576,5.103237,5.768547,8.077535,6.994130,9.724357
280,10.605813,5.395294,6.059823,3.663578,6.386645,6.092674,7.847053,5.353460,9.907040,8.214913,...,11.235925,6.565320,6.950443,6.015308,4.982558,7.450716,5.189754,8.722749,6.211883,5.663975
281,11.936951,6.095392,17.358260,10.167120,14.904716,15.795442,8.992487,6.764204,18.179725,11.047927,...,12.562684,7.471525,15.028740,12.478775,16.131465,8.508400,6.141260,10.267048,8.214864,14.916678

In [15]:
adata = sc.read_h5ad('generated_data/example/adata.h5ad')

In [16]:
adata

AnnData object with n_obs × n_vars = 2000 × 1087
    obs: 'condition', 'cell_type', 'intervention_gene_id', 'intervention_gene_name', 'intervention_comm'
    var: 'gene_id', 'kind', 'community', 'principal_reg_comm'
    uns: 'grn_dir', 'interventions'
    varp: 'grn_K'

In [17]:
adata.obs

,condition,cell_type,intervention_gene_id,intervention_gene_name,intervention_comm
unperturbed_0,unperturbed,1,NaN,NaN,NaN
unperturbed_1,unperturbed,1,NaN,NaN,NaN
unperturbed_2,unperturbed,1,NaN,NaN,NaN
unperturbed_3,unperturbed,1,NaN,NaN,NaN
unperturbed_4,unperturbed,1,NaN,NaN,NaN
...,...,...,...,...,...
pert_c4_195,perturbed,1,85.0,TF_c4_n15,4.0
pert_c4_196,perturbed,1,85.0,TF_c4_n15,4.0
pert_c4_197,perturbed,1,85.0,TF_c4_n15,4.0
pert_c4_198,perturbed,1,85.0,TF_c4_n15,4.0
pert_c4_199,perturbed,1,85.0,TF_c4_n15,4.0

In [18]:
adata.var

           gene_id kind  community  principal_reg_comm
gene_name
TF_c0_n0         0   TF          0                 NaN
TF_c0_n1         1   TF          0                 NaN
TF_c0_n2         2   TF          0                 NaN
TF_c0_n3         3   TF          0                 NaN
TF_c0_n4         4   TF          0                 NaN
...            ...  ...        ...                 ...
TG_995        1082   TG          0                 0.0
TG_996        1083   TG          1                 1.0
TG_997        1084   TG          4                 4.0
TG_998        1085   TG          3                 3.0
TG_999        1086   TG          4                 4.0

[1087 rows x 4 columns]

In [19]:
print(adata.varp['grn_K'][0:9, 0:9])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (9, 9)>
  Coords	Values
  (0, 4)	3.6816180572503128
  (0, 5)	2.015076510095936
  (0, 6)	-4.078915381321002
  (0, 7)	-4.7998292371372
  (0, 8)	3.5647985389733647
  (1, 4)	2.3675574276112816
  (1, 5)	-3.819229330231401
  (1, 6)	3.3018057488941213
  (1, 7)	2.6360835515066867
  (1, 8)	4.609717801670962
  (2, 5)	2.702084525920624
  (2, 7)	4.000716160052631
  (3, 5)	2.042238989848672
  (3, 6)	-4.658221901286575
  (3, 8)	-2.72037986135456

In [9]:
adata.X

array([[ 4.59685651,  5.53638149,  3.45418814, ...,  2.55259566,
        15.37004682, 13.34231605],
       [ 5.23178827,  5.21542406,  3.66859578, ...,  3.00249802,
        15.68553817, 13.83622306],
       [ 6.03073302,  3.63980499,  3.6053947 , ...,  1.68809488,
        20.52663332, 13.37461211],
       ...,
       [ 6.29902601,  1.55519255,  3.28113757, ...,  3.26481639,
        14.40811999, 13.73134503],
       [ 6.83905713,  1.83771168,  2.84886362, ...,  2.97478331,
        13.25901806, 14.32760746],
       [ 6.34074691,  2.01965753,  3.22949783, ...,  4.17679209,
        14.15006295, 12.49259557]])

In [13]:
np.max(adata.X[adata.X>0])

np.float64(21.951090228633397)

In [14]:
%run ./code/1_sergio_grn_gen.py --out ./generated_data/example --n_targets 1000
%run ./code/2_run_sergio.py --grn_dir ./generated_data/example --out ./generated_data/example/adata.h5ad  --n_unperturbed 1000 --n_perturbed 200

Built DAG with 87 TFs in 5 communities and 1000 targets.
Edges: TF->TF=267, TF->TG=3451
Files: input_targets.txt, input_regs.txt (variable-length, comma-separated); plus nodes/edges CSVs and README.csv
Start simulating new level
There are 1 genes to simulate in this layer
Start simulating new level
There are 1 genes to simulate in this layerStart simulating new level

Start simulating new level
Start simulating new levelThere are 1 genes to simulate in this layerStart simulating new levelThere are 1 genes to simulate in this layer



There are 1 genes to simulate in this layerThere are 1 genes to simulate in this layer

Done with current level
Start simulating new level
There are 11 genes to simulate in this layerDone with current level

Start simulating new level
Done with current levelThere are 11 genes to simulate in this layer

Start simulating new level
Done with current levelThere are 11 genes to simulate in this layer
Done with current level
Start simulating new level

Start simulating new levelThere are 11 genes to simulate in this layer

There are 11 genes to simulate in this layer
Done with current level
Start simulating new level
There are 11 genes to simulate in this layer
Done with current level
Start simulating new level
Done with current levelThere are 12 genes to simulate in this layer
Start simulating new level

Done with current levelThere are 12 genes to simulate in this layer
Done with current level
Start simulating new level

Start simulating new level
There are 12 genes to simulate in this layer
There are 12 genes to simulate in this layer
Done with current level
Start simulating new level
There are 12 genes to simulate in this layer
Done with current level
Start simulating new level
There are 34 genes to simulate in this layer
Done with current level
Start simulating new level
There are 34 genes to simulate in this layer
Done with current level
Start simulating new level
There are 34 genes to simulate in this layer
Done with current level
Start simulating new level
There are 34 genes to simulate in this layer
Done with current level
Start simulating new level
There are 33 genes to simulate in this layer
Done with current level
Start simulating new level
There are 12 genes to simulate in this layer
Done with current level
Start simulating new level
Done with current level
There are 29 genes to simulate in this layerStart simulating new level

There are 30 genes to simulate in this layer
Done with current level
Done with current levelStart simulating new level

Start simulating new level
There are 29 genes to simulate in this layer
There are 29 genes to simulate in this layer
Done with current level
Start simulating new level
There are 29 genes to simulate in this layer
Done with current level
Start simulating new level
There are 34 genes to simulate in this layer
Done with current level
Start simulating new level
There are 1000 genes to simulate in this layer
Done with current level
Start simulating new level
Done with current level
Start simulating new level
Done with current level
Start simulating new level
Done with current level
Start simulating new level
There are 1000 genes to simulate in this layer
There are 1000 genes to simulate in this layer
There are 1000 genes to simulate in this layer
There are 1000 genes to simulate in this layer
Done with current level
Start simulating new level
There are 29 genes to simulate in this layer
Done with current level
Start simulating new level
There are 1000 genes to simulate in this layer
Done with current level
Done with current level
Done with current level
Done with current level
Done with current level
Done with current level
Wrote generated_data/example/adata.h5ad with 2000 cells and 1087 genes.
Interventions folder: generated_data/example/interventions
Used 6 parallel worker(s).